'use client';
import type { BranchDto, ClassDto, ClassScheduleInputDto, CreateClassDto, DanceTypeDto, DayOfWeekDto, RoomDto, TeacherListDto } from '@academy/contracts';
import { FormEvent, useEffect, useMemo, useState } from 'react'; import { ApiClientError, apiRequest } from '../lib/api-client'; import { dayLabels } from '../lib/offering';
type UiSchedule = ClassScheduleInputDto & { branchId: string }; const days = Object.keys(dayLabels) as DayOfWeekDto[];
export function ClassForm({ academicClass, onSaved, onCancel }: Readonly<{ academicClass?: ClassDto; onSaved(value: ClassDto): void; onCancel?(): void }>) {
  const [danceTypes, setDanceTypes] = useState<readonly DanceTypeDto[]>([]); const [teachers, setTeachers] = useState<TeacherListDto['items']>([]); const [branches, setBranches] = useState<readonly BranchDto[]>([]); const [rooms, setRooms] = useState<readonly RoomDto[]>([]);
  const [form, setForm] = useState({ name: academicClass?.name ?? '', danceTypeId: academicClass?.danceType.id ?? '', teacherId: academicClass?.teacher.id ?? '', level: academicClass?.level ?? '', capacity: academicClass?.capacity ?? 1 });
  const [schedules, setSchedules] = useState<UiSchedule[]>(academicClass?.schedules.map((s) => ({ dayOfWeek: s.dayOfWeek, startTime: s.startTime, endTime: s.endTime, roomId: s.room.id, branchId: s.room.branch.id })) ?? []); const [draft, setDraft] = useState<UiSchedule>({ dayOfWeek: 'MONDAY', startTime: '18:00', endTime: '19:00', roomId: '', branchId: '' }); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([apiRequest<DanceTypeDto[]>('/dance-types?status=ACTIVE'), apiRequest<TeacherListDto>('/teachers?status=ACTIVE&page=1&pageSize=100'), apiRequest<BranchDto[]>('/branches?status=ACTIVE'), apiRequest<RoomDto[]>('/rooms?status=ACTIVE')]).then(([d, t, b, r]) => { setDanceTypes(d); setTeachers(t.items); setBranches(b); setRooms(r); setForm((f) => ({ ...f, danceTypeId: f.danceTypeId || d[0]?.id || '', teacherId: f.teacherId || t.items[0]?.id || '' })); setDraft((s) => ({ ...s, branchId: s.branchId || b[0]?.id || '' })); }); }, []);
  const branchRooms = useMemo(() => rooms.filter((room) => room.branchId === draft.branchId), [rooms, draft.branchId]);
  function addSchedule() { const roomId = draft.roomId || branchRooms[0]?.id; if (!roomId) { setMessage('Seleccioná una sucursal con salones activos'); return; } setSchedules([...schedules, { ...draft, roomId }]); setMessage(''); }
  async function submit(e: FormEvent) { e.preventDefault(); if (!schedules.length) { setMessage('Agregá al menos un horario'); return; } setSaving(true); setMessage(''); const payload: CreateClassDto = { ...form, schedules: schedules.map(({ branchId: _branchId, ...schedule }) => schedule) }; try { onSaved(await apiRequest<ClassDto>(academicClass ? `/classes/${academicClass.id}` : '/classes', { method: academicClass ? 'PATCH' : 'POST', body: JSON.stringify(payload) })); } catch (error) { setMessage(error instanceof ApiClientError ? error.message : 'No se pudo guardar la clase'); } finally { setSaving(false); } }
  return <form className="class-form" onSubmit={submit}><div className="student-form"><label>Nombre<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Tipo de danza<select value={form.danceTypeId} onChange={(e) => setForm({ ...form, danceTypeId: e.target.value })}>{danceTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Profesor<select value={form.teacherId} onChange={(e) => setForm({ ...form, teacherId: e.target.value })}>{teachers.map((item) => <option key={item.id} value={item.id}>{item.lastName}, {item.firstName}</option>)}</select></label><label>Nivel<input value={form.level} onChange={(e) => setForm({ ...form, level: e.target.value })} /></label><label>Cupo<input type="number" min="1" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: Number(e.target.value) })} /></label></div><fieldset><legend>Horarios</legend><div className="schedule-builder"><label>Día<select value={draft.dayOfWeek} onChange={(e) => setDraft({ ...draft, dayOfWeek: e.target.value as DayOfWeekDto })}>{days.map((day) => <option key={day} value={day}>{dayLabels[day]}</option>)}</select></label><label>Desde<input type="time" value={draft.startTime} onChange={(e) => setDraft({ ...draft, startTime: e.target.value })} /></label><label>Hasta<input type="time" value={draft.endTime} onChange={(e) => setDraft({ ...draft, endTime: e.target.value })} /></label><label>Sucursal<select value={draft.branchId} onChange={(e) => setDraft({ ...draft, branchId: e.target.value, roomId: '' })}>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Salón<select value={draft.roomId} onChange={(e) => setDraft({ ...draft, roomId: e.target.value })}><option value="">Seleccionar</option>{branchRooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" onClick={addSchedule}>Agregar horario</button></div><ul className="schedule-list">{schedules.map((schedule, index) => <li key={`${schedule.dayOfWeek}-${schedule.startTime}-${index}`}>{dayLabels[schedule.dayOfWeek]} {schedule.startTime}–{schedule.endTime} · {rooms.find((room) => room.id === schedule.roomId)?.name ?? 'Salón'} <button type="button" className="secondary" onClick={() => setSchedules(schedules.filter((_, i) => i !== index))}>Quitar</button></li>)}</ul></fieldset>{message && <p className="message">{message}</p>}<div className="actions"><button disabled={saving}>{saving ? 'Guardando…' : 'Guardar clase'}</button>{onCancel && <button type="button" className="secondary" onClick={onCancel}>Cancelar</button>}</div></form>;
}
